Feature/sections form
stuyspec/content-management-system pull request #2
Opened 2017-08-01 22:30 UTC by NicholasLYang

@jkao1

2017-08-01 22:58 UTC, squirrelsquirrel78 requested changes
Small changes here and there

2017-08-01 22:58 UTC, jkao1 commented on src/js/modules/forms/components/SectionForm.js
> +    paddingBottom: "2%"
These all should be margins, not paddings. Not only is margin more intuitive (margin is outside the element and its border whereas padding is inside), vertical margins auto-collapse. That means that you can do `margin: 2% 0` for all three inputs and the margin won't add up to 4%—it'll be 2%.

Also, why are you using percentages? Just use constants.

2017-08-01 22:58 UTC, jkao1 commented on src/js/modules/sections/selectors.js
> +
you know how i would name selectors, but this fine ig. just thinkinh out loud.

2017-08-01 22:58 UTC, jkao1 commented on src/js/modules/forms/components/SectionForm.js
> +}                                   from '../../sections/selectors'
you really should import the sections module, then get selectors

2017-08-02 19:12 UTC, NicholasLYang commented on src/js/modules/forms/components/SectionForm.js
> +    paddingBottom: "2%"
Changed to margin. I'm using percents for now. If they become a problem, I'll switch to constants

2017-08-02 19:20 UTC, squirrelsquirrel78 approved these changes

2017-08-02 19:21 UTC, merged