Refactor/refactor modules
stuyspec/content-management-system pull request #6
Opened 2017-08-11 04:06 UTC by NicholasLYang

Large PR. Basically refactored modules, got CRD working for articles, C for sections

2017-08-13 21:29 UTC, JasonLin43212 commented on src/js/modules/articles/components/ArticleForm.js
> +  validateForm = ({ title, content, sections, section, contributors }) => {
Fix the errors for filling out the text box.

2017-08-15 17:18 UTC, JasonLin43212 commented on src/js/modules/articles/components/ArticlesTable.js
> +    maxWidth: "800px",
CSS properties should be in alphabetical order right?

2017-08-15 17:20 UTC, JasonLin43212 commented on src/js/modules/articles/components/CreateArticlePage.js
> +        zDepth={2}
what is zDepth?

2017-08-15 18:03 UTC, jkao1 commented on src/js/modules/articles/components/ArticlesTable.js
> +    maxWidth: "800px",
yup

2017-08-15 18:43 UTC, squirrelsquirrel78 requested changes
(1) Some of your naming doesn't follow convention: https://medium.com/@kylpo/redux-best-practices-eef55a20cc72.
(2) Style: react things should be in double quotes (import statements). Other JS things are find in single quotes.

2017-08-15 18:43 UTC, jkao1 commented on src/js/modules/RoutingApp.js
> +                <Route path="/sections/new" component={SectionForm} />
It's a little inconsistent. I would expect `/articles/new` and `/sections/new` to be either named CreateArticlePage and CreateSection or ArticleForm and SectionForm.

2017-08-15 18:43 UTC, jkao1 commented on src/js/modules/articles/components/ArticleForm.js
> +      section: 2
Not sure what `section: 2` is supposed to do. If it's a default for drafts, maybe this should be made clearer with a constant or a comment.

2017-08-15 18:43 UTC, jkao1 commented on src/js/modules/articles/components/ArticlesList.js
> +  articles: state.forms.list
A little confusing. So articles are stored in forms not articles?

2017-08-15 18:43 UTC, jkao1 commented on src/js/modules/forms/reducer.js
> +
If nothing happens, just return state.

2017-08-15 18:43 UTC, jkao1 commented on src/js/modules/authorships/selectors.js
> +export const contributorsByArticle = createSelector(
Naming please.

2017-08-15 18:43 UTC, jkao1 commented on src/js/modules/main/components/MainApp.js
> +    } = this.props
semicolon

2017-08-15 18:43 UTC, jkao1 commented on src/js/modules/main/components/MainApp.js
> +        dispatch(fetchUsers())
why? `mapDispatchToProps`???

2017-08-15 18:43 UTC, jkao1 commented on src/js/modules/sections/actionTypes.js
> +export const CREATE_SECTION_FAILED = 'forms/CREATE_SECTION_FAILED';
Again, the action naming I mentioned earlier. Please consider it.

2017-08-15 18:43 UTC, jkao1 commented on src/js/modules/sections/components/SectionForm.js
> +import { topLevelSectionsSelector } from '../selectors'
Just a reminder about one of my first comments: double quotes vs. single quotes.

2017-08-18 04:18 UTC, NicholasLYang commented on src/js/modules/RoutingApp.js
> +                <Route path="/sections/new" component={SectionForm} />
Yep, will fix in next branch. When I add editing sections

2017-08-18 04:18 UTC, NicholasLYang commented on src/js/modules/articles/components/ArticlesList.js
> +  articles: state.forms.list
...oops. ArticleList will be deprecated soon

2017-08-18 04:22 UTC, NicholasLYang commented on src/js/modules/forms/reducer.js
> +
Shouldn't it do that? Switch breaks then returns state

2017-08-18 04:23 UTC, NicholasLYang commented on src/js/modules/main/components/MainApp.js
> +        dispatch(fetchUsers())
Yeah yeah

2017-08-18 04:24 UTC, jkao1 commented on src/js/modules/forms/reducer.js
> +
yea yea

2017-08-20 02:07 UTC, merged