Feature/section table
stuyspec/content-management-system pull request #7
Opened 2017-08-28 17:38 UTC by NicholasLYang

2017-08-28 18:40 UTC, squirrelsquirrel78 requested changes

2017-08-28 18:40 UTC, squirrelsquirrel78 commented on src/js/modules/articles/selectors.js
> +export const getSelectedArticles = state => state.articles.list;
Inaccurate name.

2017-08-28 18:40 UTC, jkao1 commented on src/js/modules/sections/actionTypes.js
This is small but...doubles + singles quotations lol

2017-08-28 18:40 UTC, jkao1 commented on src/js/modules/sections/actions.js
> +      dispatch(push("/"));
As a user, I want to be redirected to the SectionTable after I finish creating a section.

2017-08-29 19:53 UTC, NicholasLYang commented on src/js/modules/articles/selectors.js
> +export const getSelectedArticles = state => state.articles.list;
Oops idk why that happened

2017-08-29 21:28 UTC, merged